import { asString, byType, sanitizeField } from "./format"
import type { CircuitElement, SourceGroupId } from "./types"

type ClassMemberKind = "component" | "net"

export function createPcbClassRecords(circuitJson: CircuitElement[]): string[] {
  const sourceGroups = new Map<SourceGroupId, CircuitElement>(
    byType(circuitJson, "source_group").flatMap((sourceGroup) => {
      const sourceGroupId = asString(sourceGroup.source_group_id)
      return sourceGroupId ? [[sourceGroupId, sourceGroup]] : []
    }),
  )
  const componentMembers = new Map<SourceGroupId, string[]>()
  for (const sourceComponent of byType(circuitJson, "source_component")) {
    appendClassMember({
      classMembers: componentMembers,
      memberName: asString(sourceComponent.name),
      sourceGroupId: asString(sourceComponent.source_group_id),
    })
  }
  const netMembers = new Map<SourceGroupId, string[]>()
  for (const sourceNet of byType(circuitJson, "source_net")) {
    const memberSourceGroupIds = Array.isArray(
      sourceNet.member_source_group_ids,
    )
      ? sourceNet.member_source_group_ids
      : []
    for (const sourceGroupId of memberSourceGroupIds) {
      appendClassMember({
        classMembers: netMembers,
        memberName: asString(sourceNet.name),
        sourceGroupId: asString(sourceGroupId),
      })
    }
  }

  const recordSources: string[] = []
  for (const [sourceGroupId, sourceGroup] of sourceGroups) {
    const className =
      sanitizeField(sourceGroup.name) || sanitizeField(sourceGroupId)
    for (const memberKind of ["component", "net"] as const) {
      const members =
        memberKind === "component"
          ? componentMembers.get(sourceGroupId)
          : netMembers.get(sourceGroupId)
      if (!members?.length) continue
      recordSources.push(
        createClassRecord({
          className,
          memberKind,
          members,
          sourceGroupId,
        }),
      )
    }
  }
  return recordSources
}

function appendClassMember({
  classMembers,
  memberName,
  sourceGroupId,
}: {
  classMembers: Map<SourceGroupId, string[]>
  memberName: string
  sourceGroupId: SourceGroupId
}): void {
  if (!sourceGroupId || !memberName) return
  const members = classMembers.get(sourceGroupId) ?? []
  members.push(memberName)
  classMembers.set(sourceGroupId, members)
}

function createClassRecord({
  className,
  memberKind,
  members,
  sourceGroupId,
}: {
  className: string
  memberKind: ClassMemberKind
  members: string[]
  sourceGroupId: SourceGroupId
}): string {
  return [
    "|RECORD=Class",
    `KIND=${memberKind === "component" ? "1" : "0"}`,
    `NAME=${className}`,
    "SUPERCLASS=FALSE",
    "AUTOGENERATEDCLASS=FALSE",
    ...members.map(
      (memberName, memberIndex) =>
        `M${memberIndex}=${sanitizeField(memberName)}`,
    ),
    `UNIQUEID=${sanitizeField(`${sourceGroupId}-${memberKind}`)}`,
  ].join("|")
}
