import type { AltiumPcbDocument } from "altiumts"
import type {
  CircuitElement,
  ComponentDesignator,
  PcbNetName,
  SourceGroupId,
} from "../../lib/types"

export type AltiumPcbClassMembership = {
  componentGroupIdByDesignator: Map<ComponentDesignator, SourceGroupId>
  netGroupIdsByName: Map<PcbNetName, SourceGroupId[]>
  sourceGroups: CircuitElement[]
}

export function getAltiumPcbClassMembership(
  document: AltiumPcbDocument,
): AltiumPcbClassMembership {
  const componentGroupIdByDesignator = new Map<
    ComponentDesignator,
    SourceGroupId
  >()
  const netGroupIdsByName = new Map<PcbNetName, SourceGroupId[]>()
  const sourceGroups: CircuitElement[] = []
  const componentDesignators = new Set(
    document.components.flatMap((component) =>
      component.designator ? [component.designator] : [],
    ),
  )
  const netNames = new Set(
    document.nets.flatMap((net) => (net.name ? [net.name] : [])),
  )

  for (const [classIndex, classRecord] of document
    .getRecordsByKind("Class")
    .entries()) {
    if (
      classRecord.getBoolean("SUPERCLASS") === true ||
      classRecord.getBoolean("AUTOGENERATEDCLASS") === true
    ) {
      continue
    }
    const classKind = classRecord.getNumber("KIND")
    if (classKind !== 0 && classKind !== 1) continue
    const sourceGroupId = `source_group_class_${classIndex}`
    let acceptedMemberCount = 0
    for (const memberName of getClassMemberNames(classRecord)) {
      if (classKind === 1) {
        if (
          componentDesignators.has(memberName) &&
          !componentGroupIdByDesignator.has(memberName)
        ) {
          componentGroupIdByDesignator.set(memberName, sourceGroupId)
          acceptedMemberCount++
        }
        continue
      }
      if (!netNames.has(memberName)) continue
      const sourceGroupIds = netGroupIdsByName.get(memberName) ?? []
      sourceGroupIds.push(sourceGroupId)
      netGroupIdsByName.set(memberName, sourceGroupIds)
      acceptedMemberCount++
    }
    if (acceptedMemberCount === 0) continue
    sourceGroups.push({
      type: "source_group",
      source_group_id: sourceGroupId,
      name: classRecord.getDecoded("NAME") ?? sourceGroupId,
    })
  }

  return {
    componentGroupIdByDesignator,
    netGroupIdsByName,
    sourceGroups,
  }
}

function getClassMemberNames(classRecord: {
  getDecoded: (fieldName: string) => string | undefined
}): string[] {
  const memberNames: string[] = []
  for (let memberIndex = 0; memberIndex < 100_000; memberIndex++) {
    const memberName = classRecord.getDecoded(`M${memberIndex}`)
    if (memberName === undefined) break
    memberNames.push(memberName)
  }
  return memberNames
}
